// Package sqlite wraps code generated by sqlc, so there is
// no need to convert data types from SQLite to Go and vice versa.
package sqlite

import (
	"github.com/axseem/learway/storage"
	"github.com/axseem/learway/storage/sqlite/sqlc"
)

// New creates a new SQLite queries instance.
func New(db sqlc.DBTX) *storage.Queries {
	queries := sqlc.New(db)

	return &storage.Queries{
		Deck:    NewDeckStorage(queries),
		Session: NewSessionStorage(queries),
		User:    NewUserStorage(queries),
	}
}
