// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.25.0

package database

import (
	"time"
)

type Deck struct {
	ID        int64
	Title     string
	Cards     string
	CreatedAt time.Time
	UpdatedAt time.Time
}
