// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.26.0

package sqlc

import (
	"net"
	"time"
)

type Deck struct {
	ID        string
	UserID    string
	Title     string
	Cards     []byte
	CreatedAt time.Time
	UpdatedAt time.Time
}

type Session struct {
	ID          string
	UserID      string
	Fingerprint []byte
	IP          net.IP
	ExpiresAt   time.Time
	CreatedAt   time.Time
}

type User struct {
	ID        string
	Username  string
	Email     string
	Password  []byte
	CreatedAt time.Time
}
