CREATE TABLE
    deck (
        id TEXT PRIMARY KEY,
        title TEXT NOT NULL,
        cards BLOB NOT NULL,
        created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
        updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP
    );